import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const validationSource = await readFile(new URL('../portal/services/checkin-validation.js', import.meta.url), 'utf8');
const {
    CheckinValidationError,
    getCheckinErrorMessage,
    isSafeDocumentId,
    normalizeCheckinPassState,
    parseQrPayload,
    validPassCount
} = await import(`data:text/javascript;base64,${Buffer.from(validationSource).toString('base64')}`);

test('normaliza primer check-in de invitado legado sin contadores', () => {
    assert.deepEqual(normalizeCheckinPassState({ pases: 3 }), {
        pasesTotales: 3,
        pasesUtilizados: 0,
        pasesDisponibles: 3
    });
});

test('infiere usados cuando el invitado legado solo tiene disponibles', () => {
    assert.deepEqual(normalizeCheckinPassState({ pases: '4', pasesDisponibles: '2' }), {
        pasesTotales: 4,
        pasesUtilizados: 2,
        pasesDisponibles: 2
    });
});

test('preserva un legado ya marcado como llegado sin contadores', () => {
    assert.deepEqual(normalizeCheckinPassState({ pases: 2, estado: 'llego' }), {
        pasesTotales: 2,
        pasesUtilizados: 2,
        pasesDisponibles: 0
    });
});

test('rechaza contadores incoherentes en lugar de registrar de más', () => {
    assert.throws(
        () => normalizeCheckinPassState({ pases: 2, pasesUtilizados: 0, pasesDisponibles: 1 }),
        (error) => error instanceof CheckinValidationError && error.code === 'checkin/invalid-guest-pass-data'
    );
});

test('acepta pases enteros y rechaza excedentes o fracciones', () => {
    assert.equal(validPassCount('2'), 2);
    assert.equal(validPassCount(1.5), null);
    assert.equal(validPassCount(0), null);
    assert.equal(validPassCount(1_000), null);
});

test('acepta token directo, URL y JSON documentados', () => {
    const token = 'Abcdefghijklmnop_1234';
    assert.deepEqual(parseQrPayload(token), { token, eventId: null });
    assert.deepEqual(parseQrPayload(`https://eventorastudio.com/pase?t=${token}&eventId=EVT-0001`), { token, eventId: 'EVT-0001' });
    assert.deepEqual(parseQrPayload(JSON.stringify({ eventId: 'EVT-0001', token })), { token, eventId: 'EVT-0001' });
});

test('no acepta INV-0001 ni otros tokens QR inseguros', () => {
    assert.throws(
        () => parseQrPayload('INV-0001'),
        (error) => error instanceof CheckinValidationError && error.code === 'checkin/invalid-qr-format'
    );
});

test('el mapper no confunde permisos, sesión o datos inválidos con conexión', () => {
    assert.equal(getCheckinErrorMessage({ code: 'permission-denied' }), 'No tienes permisos para registrar entradas en este evento.');
    assert.equal(getCheckinErrorMessage({ code: 'unauthenticated' }), 'Tu sesión terminó. Inicia sesión nuevamente.');
    assert.equal(getCheckinErrorMessage({ code: 'invalid-argument' }), 'Los datos de entrada no son válidos.');
    assert.equal(getCheckinErrorMessage({ code: 'unavailable' }), 'No fue posible conectar con el servidor.');
});

test('el ID de documento, no el código visible, es una referencia segura', () => {
    assert.equal(isSafeDocumentId('INV-0001'), true);
    assert.equal(isSafeDocumentId('autoGeneratedGuestId'), true);
    assert.equal(isSafeDocumentId('codigo/visible'), false);
});
