import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getToken } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app-check.js';
import { auth, appCheck } from './firebase.js';
import { apiFetch, isTimeoutError } from '../../shared/api.js';

const base = 'https://us-central1-eventorastudio-d6d95.cloudfunctions.net';
const labels = { new:'Nuevo', review:'Por revisar', ready_to_contact:'Listo para contactar', contacted:'Contactado', follow_up:'Seguimiento pendiente', responded:'Respondió', interested:'Interesado', proposal:'Cotización enviada', negotiation:'Negociación', client:'Cliente', not_interested:'No interesado', no_response:'Sin respuesta', discarded:'Descartado' };
const initialProspects = [
  { businessName:'Dorcha Café', category:'Cafetería', city:'Emilio Arizpe / sur', email:'dorchacafe23@gmail.com', contactStatus:'contacted', channel:'Email', package:'Profesional', priceReference:'$999 MXN', promotionEligible:true, promotion:'hosting-maintenance-60-free-2026', priority:'ALTA', proposal:'Menú, galería del ambiente, reservaciones para festejos, ubicación, horarios y WhatsApp.', angle:'Convertir sus visitas y reservaciones en una experiencia más profesional desde un solo enlace.', firstContactAt:'2026-10-08', lastContactAt:'2026-10-08', nextFollowUpAt:'2026-10-11', notes:'Primer contacto: correo enviado. Respuesta pendiente.' },
  { businessName:'Cafetería Kala', category:'Cafetería', city:'Paseo Capital / Centro', email:'cafet.kala@gmail.com', contactStatus:'contacted', channel:'Email', package:'Profesional', priceReference:'$999 MXN', promotionEligible:true, promotion:'hosting-maintenance-60-free-2026', priority:'ALTA', proposal:'Menú digital, promociones, horarios, ubicación, galería y WhatsApp.', angle:'Que sus clientes encuentren rápidamente qué ofrecen, cuánto cuesta y cómo llegar.', firstContactAt:'2026-10-08', lastContactAt:'2026-10-08', nextFollowUpAt:'2026-10-11', notes:'Primer contacto: correo enviado. Respuesta pendiente.' },
  { businessName:'Cafetto Ventus', category:'Cafetería', city:'Centro / Plaza Arcada', email:'Cafettoventus@gmail.com', contactStatus:'contacted', channel:'Email', package:'Esencial', priceReference:'$599 MXN', promotionEligible:true, promotion:'hosting-maintenance-60-free-2026', priority:'MEDIA/ALTA', proposal:'Sitio esencial con identidad de marca, productos principales, ubicación, horarios y WhatsApp.', angle:'Presentar la marca y facilitar que nuevos clientes los encuentren y contacten.', firstContactAt:'2026-10-08', lastContactAt:'2026-10-08', nextFollowUpAt:'2026-10-11', notes:'Primer contacto: correo enviado. Respuesta pendiente.' },
  { businessName:'Bon Cake', category:'Pastelería', city:'República Oriente', email:'boncake@hotmail.com', contactStatus:'contacted', channel:'Email', package:'Profesional', priceReference:'$999 MXN', promotionEligible:true, promotion:'hosting-maintenance-60-free-2026', priority:'MUY ALTA', proposal:'Catálogo visual, portafolio de pasteles, mesas de postres, paquetes, cotizaciones y WhatsApp.', angle:'Transformar su alcance en redes en más cotizaciones organizadas y ventas para eventos.', firstContactAt:'2026-10-08', lastContactAt:'2026-10-08', nextFollowUpAt:'2026-10-11', notes:'Primer contacto: correo enviado. Respuesta pendiente.' }
];
let user = null; let prospects = []; let editing = null;
const $ = (selector) => document.querySelector(selector); const list = $('#list'); const dialog = $('#dialog'); const form = $('#form');
ensurePromotionFields();

function ensurePromotionFields() {
  if (form.elements.promotion) return;
  const grid = form.querySelector('.grid');
  const eligible = document.createElement('label'); eligible.textContent = 'Promoción elegible'; const checkbox = document.createElement('input'); checkbox.name = 'promotionEligible'; checkbox.type = 'checkbox'; eligible.append(checkbox);
  const code = document.createElement('label'); code.textContent = 'Código de promoción'; const input = document.createElement('input'); input.name = 'promotion'; input.value = 'hosting-maintenance-60-free-2026'; code.append(input);
  grid.append(eligible, code);
}

onAuthStateChanged(auth, async (next) => { user = next; if (!user) { if (window.top === window.self) location.replace('/admin/#prospeccion'); return; } await load(); });
$('#refresh').addEventListener('click', load); $('#search').addEventListener('input', render); $('#status-filter').addEventListener('change', render); $('#new').addEventListener('click', () => openForm()); $('#close').addEventListener('click', () => dialog.close()); $('#cancel').addEventListener('click', () => dialog.close()); form.addEventListener('submit', save);

async function load() { setStatus('Cargando...'); try { const result = await request('/getProspects'); prospects = result.prospects || []; if (!prospects.length) { await request('/seedProspects', { method:'POST', body:JSON.stringify({ prospects: initialProspects }) }); const seeded = await request('/getProspects'); prospects = seeded.prospects || []; } render(); setStatus(''); } catch (error) { setStatus(error.message || 'No pudimos cargar la prospección.'); } }
async function request(path, options = {}) { try { return await apiFetch(`${base}${path}`, { user, appCheck, getAppCheckToken: getToken, options }); } catch (error) { if (isTimeoutError(error)) throw new Error('La solicitud está tardando demasiado. Intenta nuevamente.'); throw error; } }
function render() { const query = $('#search').value.trim().toLowerCase(); const filter = $('#status-filter').value; const rows = prospects.filter((item) => (!query || [item.businessName,item.category,item.city,item.email].join(' ').toLowerCase().includes(query)) && (filter === 'all' || item.contactStatus === filter)); const summary = $('#summary'); summary.replaceChildren(); Object.entries({total:prospects.length, nuevos:prospects.filter((x)=>x.contactStatus==='new').length, contactados:prospects.filter((x)=>x.contactStatus==='contacted').length, seguimiento:prospects.filter((x)=>x.nextFollowUpAt).length}).forEach(([key,value]) => { const article=document.createElement('article'); const strong=document.createElement('strong'); strong.textContent=value; const span=document.createElement('span'); span.textContent=key; article.append(strong,span); summary.append(article); }); list.replaceChildren(); if (!rows.length) { const empty=document.createElement('p'); empty.className='empty'; empty.textContent='No hay prospectos con estos filtros.'; list.append(empty); return; } rows.forEach((item) => { const card=document.createElement('article'); card.className='card'; const header=document.createElement('div'); const pill=document.createElement('span'); pill.className='pill'; pill.textContent=labels[item.contactStatus] || item.contactStatus; const title=document.createElement('h2'); title.textContent=item.businessName; const description=document.createElement('p'); description.textContent=`${item.category || 'Sin categoría'} · ${item.city || 'Saltillo'}`; header.append(pill,title,description); const meta=document.createElement('div'); meta.className='meta'; const pack=document.createElement('span'); pack.textContent=`${item.package || 'Sin paquete'} · ${item.priceReference || 'Sin precio'}`; const contact=document.createElement('span'); contact.textContent=item.email || item.phone || 'Sin contacto'; meta.append(pack,contact); const actions=document.createElement('div'); actions.className='card-actions'; const edit=document.createElement('button'); edit.className='button light'; edit.textContent='Editar'; const remove=document.createElement('button'); remove.className='button danger'; remove.textContent='Eliminar'; edit.addEventListener('click', () => openForm(item)); remove.addEventListener('click', async () => { if (!confirm(`¿Eliminar ${item.businessName}?`)) return; await request('/deleteProspect', {method:'POST',body:JSON.stringify({id:item.id})}); await load(); }); actions.append(edit,remove); card.append(header,meta,actions); list.append(card); }); }
function openForm(item = null) { editing = item; $('#dialog-title').textContent = item ? 'Editar negocio' : 'Nuevo negocio'; form.reset(); form.elements.promotion.value = 'hosting-maintenance-60-free-2026'; if (item) Object.entries(item).forEach(([key,value]) => { if (!form.elements[key]) return; if (form.elements[key].type === 'checkbox') form.elements[key].checked = value === true; else form.elements[key].value = value || ''; }); dialog.showModal(); }
async function save(event) { event.preventDefault(); $('#form-status').textContent='Guardando...'; const data = Object.fromEntries(new FormData(form)); try { await request(editing ? '/updateProspect' : '/createProspect', {method:'POST', body:JSON.stringify(editing ? {...data,id:editing.id} : data)}); dialog.close(); await load(); } catch (error) { $('#form-status').textContent=error.message || 'No pudimos guardar.'; } }
function setStatus(value) { $('#status').textContent=value; }
